### ISSUE TITLE
Encapsular el objeto receta

### ISSUE THREAD

**Issue by jgaleano2018** [Nagochi1/EjercicioCocina#3]
https://github.com/Nagochi1/EjercicioCocina/blob/6b28f66d2006551266542262cdfb6c1ad8136306/src/com/bancodebogota/fdm/ejerciciococina/EjercicioCocina.java#L253

Este método se debe ubicar de primero en el bloque de la clase main.

**Comment by Nagochi1** [comment]
Issue repetido.
