### ISSUE TITLE
Este es el incidente

### ISSUE THREAD

**Issue by jgaleano2018** [Nagochi1/EjercicioCocina#6]
https://github.com/Nagochi1/EjercicioCocina/blob/6b28f66d2006551266542262cdfb6c1ad8136306/src/com/bancodebogota/fdm/ejerciciococina/Plato.java#L15

Cambiar la variable String codReceta por el objeto Receta receta

**Comment by Nagochi1** [comment]
Se realiza cambio de protected por private.
